language: node_js
node_js: 5  # Can't update to 6 until gulp does not depend on vinyl-fs 0.3.0
sudo: false

install:
  - npm install --no-spin

script:
  - npm run lint
  - npm test

notifications:
webhooks:
    urls:
      - https://webhooks.gitter.im/e/6885fd1dbe70aca78516
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
